### ISSUE TITLE
Iskraemeco AM550 problem

### ISSUE THREAD

**Issue by AdmiralStipe** [saghonfly/shrdzm#12]
Trying to use your firmware on Iskraemeco AM550 in Slovenia, but I'm getting error displayed on the General tab and also in MQTT: 
"(0)lasterror=No supported SmartMeter Type identified - first Byte does not fit". 

I tried three different cyphers (all three provided by distributor: Unicast key, Broadcast key and Authentication key), but the error is always the same. Could it be, that my meter uses different baudrate (got some success on another code, which enables baudrate change to 38400, but does not have cypherkey implemented, so I can't really use it, as It can only read headers on encypted messages)? 

I used the bin file and flashed it with NodeMCU flasher as I'm unable to compile the code myself in Arduino (a lot of missing libraries, which I'm unable to find and add).

**Comment by saghonfly** [comment]
From my experience, SmartMeters have different protocols, depending on the power provider whishes.
Even the same Samrtmeter-types seems to have different hardware and software protocols.

Could you please change on the settings-tab the value for 'sendRawData' from NO to YES.
If it is set to YES, the output should also show the read raw data how it is sent by the Smartmeter.

With this raw data, we should be able to analyse the protocol and enhance the firmware to support the Smartmeter how it is used in Slovenia.

For this activity, please use this version:
https://github.com/saghonfly/shrdzm/blob/dev/code/SHRDZMDevice/SHRDZMDevice.ino.generic.bin

**Comment by AdmiralStipe** [comment]
Thx for your prompt reply. 
I tried checking raw data already at my first attempt (was curious to see, what data do I even get out of the meter), but the strangest thing happened - the lower lines on Configuration tab (invert RX, sendRawdata, cipherkey) simply dissapeared and I couldn't get them back... all the rest was working perfectly though :). 
So I did "factory reset" and repeated the whole setup process and the same thing happened again.
 
Maybe it was a bad flash (although everything seemed to work)... will try with attached firmware and post results.

**Comment by AdmiralStipe** [comment]
Well, I tried it, but without luck. I got 
(0)lasterror=No data read
(1)uptime=0000:00:01:02

Everything else works (including MQTT messages), but it just doesn't read the data. 
The manufacturer's tehnician told me two things when I talked to him: 
1. that I should use both keys for decryption (authentication and unicast). Here I can only use one, maybe that's the issue. 
2. baud rate on my meter is most likely set to 38400. 

Would it be possible to adjust the code in a way, where bad rate can be set like other parameters (invert, raw data,...)?
Or if you can make me firmware with fixed baudrate 38400 for debugging purposes?

As already stated, I tried to compile your code myself, but even after installing all libraries, I still get a bunch of compile errors. Otherwise I would try to adjust there parameters myself, but I just can't get it to compile.

**Comment by saghonfly** [comment]
In case if 'No data read' is shown, something happens with the communication.

Let's check this first...

Do you have the possibility to read the [encrypted] data stream directly without using the ESP or even SHRDZM?
Means, can you try to connect via a serial connection directly to your PC and read out the data with eg. HTerm?

**Comment by AdmiralStipe** [comment]
Unfortunately not, I have no RJ12-USB cable. 
The only two possibilities I have at the moment are ESP8266 with protoboard or [Marcel Zuidwijk's Slimmelezer](https://www.zuidwijk.com/product/slimmelezer/), which also uses ESP8266, but has already built in input inverter and cable attached. I bought it some time ago, but is not working as it uses plain ASCII communication instead of DLMS.

**Comment by saghonfly** [comment]
Do you have gotten an official interface specification from your power provider which you could share?

In addition, would it be possible for you to upload a simple serial reader test sketch with the expected baud rate to the ESP8266 which is just listening on the incoming data stream?

**Comment by AdmiralStipe** [comment]
Yes, I have a PDF (manual) for my meter, but the file is rather big to be inserted here... can I send it to you by email? If you don't want to post your e-mail address publicly, here's mine: stipe.stipe@gmail.com . I will delete it later, after you send me the contact mail :) )

Sure, I can upload anything to both ESP8266 (or even on ESP32, if that's better or easier)... just to be noted, on the first ESP8266 (it's a clone of Wemos D1 mini) on protoboard I can freely use any pins, but the Slimmelezer one (also D1 mini) has fixed input pin on D7 (GPIO13) and it is logically inverted (it's soldered on PCB, so not changeable). 

If the sketch is written for Arduino IDE it's even better, as I can quickly change some parameters and re-flash, if needed (change of baud rate for example as I'm not 100% sure, it should be 38400... in the manual says, that default is 115200, but the technician told me, it is most likely 38400).

**Comment by saghonfly** [comment]
Please upload this test version to try whether it is working with your AM550 Smartmeter configuration in Slovenia.
[SHRDZMDevice](https://github.com/saghonfly/shrdzm/blob/2cb760a67948e74a210e587c5453b538010015dd/code/SHRDZMDevice/SHRDZMDevice.ino.generic.bin)

It looks like, the AM550 Smartmeter in Slovenia has nearly the same configuration as in Carinthia, only different baud rate and the values are on a little bit different positions.

If you upload, you will find a new parameter on the settings page where you can change the baud rate. (maybe you have to save it fist before you see it...)

**Comment by saghonfly** [comment]
Support for AM550 used in Slovenia added.
