### ISSUE TITLE
Not working if cihperkey not set

### ISSUE THREAD

**Issue by johhn2nd** [saghonfly/shrdzm#13]
Hi Erich,

Trying to use SHRDZMDevice 0.5.2. on AM550 in Slovenia where I have encryption disabled, so no need to enter cipherkey. SHRDZM reported back last error: "cipherkey not set" so don't have any values from meter. What should I do in this case? As I understand this was not jet an option probably in your program to be without encryption. Originally I have slimeleezer board where I was able to receive "ISK1serialnumber", but no values due to protocol differences as I understand your wiki.

**Comment by saghonfly** [comment]
Hello johhn2nd,

 you are right, currently, not encrypted data stream is not supported.

Do you have a specification from your energy provider company how the protocol looks like what your smartmeter provides?
Alternatively, can you enable the 'sendRawData' parameter in the settings dialog and send me the output?

**Comment by johhn2nd** [comment]
Hi Erich,

Unfortunately I don't have protocol from provider, but I think it's same for all AM550 meters in Slovenia manufactured from 2020 and above. I was trying to get encryption key from them, but they just let me know they disable encryption on P1 port for my meter. And actually with slimeleezer there was income difference as I write above, because at first try there were only symbols receiving.

If I enable sendRawData (YES) there is no difference. Still have same last error "cipherkey not set ".

**Comment by saghonfly** [comment]
HI,

 correct, enabling of senRawData will not solve the problem that current implementation is not able to deal with unencrypted data.

Unfortunately, if no cipherkey set, only output is this message.
Please try also entering any 32 byte string into the cipherkey field.

In this case, the output should show a different error but also the raw data which was read.

**Comment by johhn2nd** [comment]
**Result with random 32 numbers as cipherkey and sendRawData YES:**
(0)lasterror=No supported SmartMeter Type identified - No end Byte found
(1)uptime=0000:00:07:03
(2)data=7EA05BCF0223131A52E6E7000F0056B7770C07E6011E0709393A00FFC4000209091049534B313033303737383331333833300600000CDE06000000000600373F7506001DFEF8060019407D0600000048060000002B060000001DE3CF7E

**Result with random 32 numbers as cipherkey and sendRawData NO:**
(0)lasterror=No supported SmartMeter Type identified - No end Byte found
(1)uptime=0000:00:07:58

**Comment by saghonfly** [comment]
could you imagine that this are the values which where shown on your samrtmeter at the time when you colletd the rad data for me?

(1) 3294
(2) 0
(3) 3620725
(4) 1965816
(5) 1654909
(6) 72
(7) 43
(8) 29

The raw data does not contain a description of the parameter, so it must be known which one stands for what...

**Comment by johhn2nd** [comment]
Yes  I can recognize this three values:
(3) 3620725 - total energy consumption, on meter is 3620,72kwh
(4) 1965816 - high tariff consumption, on meter is 1965,8kwh
(5) 1654909 - low tariff consumption, on meter is 1654,9kwh

**Comment by saghonfly** [comment]
Hi,

I created a development version which should solve your problem.

Please upload the last SHRDZMDevice.ino.generic.bin from the development branch to your device.

To instruct the firmware not to try to decrypt, please enter '99999999999999999999999999999999' into the cipherkey field.

**Comment by johhn2nd** [comment]
Result with dev. version:
(0)timestamp=2022-01-30T16:43:58
(1)value1=1425
(2)value2=0
(3)value3=3625563
(4)value4=1965816
(5)value5=1659747
(6)value6=72
(7)value7=43
(8)value8=29
(9)uptime=0000:00:05:20

I watch value1 how it's changing so I do some load test and I can confirm (1)value1 =  current total power in Watts.
I'm sure there must be also for each phase voltages and amperage. This should be perfect to fetch to monitorize power per phase and balance L1-L2-L3.
